### PR TITLE
Added Known Issues & Fix SSL23_GET_SERVER_HELLO on Windows OS

### PR DESCRIPTION
**Pull request by nextco**
[+] Info to fix error on Windows OS

### CODE REVIEW

**Comment by marc-etienne** [comment]
Thanks for your contribution.

You have a good workaround to the problem, I'd rather fix it or display a better error message.

I'm guessing your Python installation doesn't support SNI. Can you tell me which version of Python you are running (`python --version` or `sys.version`)?

**Comment by nextco** [comment]
Yes I'm using IDA 6.8 default python doesn't support SNI
λ python --version
Python 2.7.6 x86

**Comment by marc-etienne** [comment]
According to http://docs.python-requests.org/en/master/community/faq/

> Python3 and Python 2.7.9+ include native support for SNI in their SSL modules.

Python change log:

> The entirety of Python 3.4's ssl module has been backported for Python 2.7.9. See PEP 466 for justification.

I check and perhaps it's not because of SNI but `subjectAltName`. Anyway I'll test with 2.7.8 and 2.7.9  and I'll display an error suggesting to update Python during the installation if it fixes it.

**Comment by nextco** [comment]
The main problem is Python for IDA 6.8 is tied to that version 2.7.6 to guarantee its compatibility. :(

**Comment by marc-etienne** [comment]
> The main problem is Python for IDA 6.8 is tied to that version 2.7.6

I don't think that's true. I was able to use Python 2.7.12 just fine with IDA 6.8.150423.

```
IDA Version 6.8.150423 (32-bit)
Python 2.7.12 (v2.7.12:d33e0cf91556, Jun 27 2016, 15:19:22) [MSC v.1500 32 bit (Intel)] 
IDAPython v1.7.0 final (serial 0)
```

I will have a proper message for Python < 2.7.9, tracked in #11.

**Pull request closed without merging**
